apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: configuration-policies
placementBindingDefaults:
  name: all-cluster-placement
policyDefaults:
  namespace: policies
  consolidateManifests: false
policies:
  - name: operator-configuration
    manifests:
      - path: manifests/operators
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
  - name: console-banner
    manifests:
      - path: manifests/console-banner
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
  - name: migrate-workloads-to-infra-nodes
    manifests:
      - path: manifests/infrastructure-nodes
        pruneObjectBehavior: None
        remediationAction: enforce
    placement:
      placementPath: placements/non-hub-placement.yaml
  - name: oauth-ldap
    manifests:
      - path: manifests/ldap
        pruneObjectBehavior: None
        remediationAction: inform
