apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: configuration-policies
policyDefaults:
  namespace: policies
  consolidateManifests: false
policies:
  - name: operator-configuration
    manifests:
      - path: manifests/operators
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
  - name: infrastructure-nodes
    manifests:
      - path: manifests/infrastructure-nodes
        pruneObjectBehavior: None
        remediationAction: inform
    placement:
      labelSelector:
        matchExpressions:
            - key: local-cluster
              operator: NotIn
              values:
                - "true"
                - "True"
#  - name: oauth-ldap
#    manifests:
#      - path: manifests/ldap
#        pruneObjectBehavior: DeleteIfCreated
#        remediationAction: inform
